version: '{build}'
branches:
  only:
  - master
  - fullduplexstream
  - /^v\d+(?:\.\d+)?$/
  - /[\b_]validate\b/
skip_tags: true
skip_commits:
  files:
    - doc/*
    - .github/*
    - '**/*.md'
    - .vsts-ci.yml
nuget:
  disable_publish_on_pr: true
image: Visual Studio 2017
configuration: Release
environment:
  VisualStudioVersion: 15.0
  codecov_token: b8be69b5-6dc3-40f8-a4c7-4e13a42654a3
build_script:
- dotnet build src
- dotnet pack src --no-build
test_script:
- cmd: >-
    SET testdir=bin\Nerdbank.Streams.Tests\%configuration%\net461\

    "%userprofile%\.nuget\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe"
    -register:user
    -target:"%xunit20%\xunit.console.x86.exe"
    -targetargs:"%testdir%Nerdbank.Streams.Tests.dll -noshadow -parallel all -notrait \"SkipInCodeCoverage=true\" -html %testdir%testresults.html -xml %testdir%testresults.xml -appveyor -nologo"
    -returntargetcode
    -excludebyattribute:*.ExcludeFromCodeCoverage*
    -excludebyfile:*\*Designer.cs
    -filter:"+[Nerdbank.Streams]*"
    -hideskipped:All
    -output:%testdir%code_coverage.xml

    SET PATH=C:\Python34;C:\Python34\Scripts;%PATH%

    pip install codecov

    codecov -f "%testdir%code_coverage.xml"

    dotnet test src\Nerdbank.Streams.Tests --no-build
artifacts:
- path: bin\**\*.nupkg
  name: NuGet Package
