version: 1.0.{build}
skip_tags: true
os: Visual Studio 2015
configuration: Release
cache:
 - '%USERPROFILE%\.nuget\packages -> **\project.json'
 - 'packages -> **\packages.config'
install:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/install-nuget-3-3-0.ps1'))
before_build:
- ps: nuget restore src
artifacts:
- path: bin\**\*.nupkg
