trigger:
  branches:
    include: ["master", "v2.*", "*_validate"]
  paths:
    exclude: ["doc", "*.md"]

variables:
  TreatWarningsAsErrors: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  BuildPlatform: Any CPU
  codecov_token: b8be69b5-6dc3-40f8-a4c7-4e13a42654a3

jobs:
- job: Windows
  pool: Hosted Windows 2019 with VS2019
  steps:
  - template: azure-pipelines/install-dependencies.yml

  - script: |
      dotnet tool install --tool-path .. nbgv
      ..\nbgv cloud
    workingDirectory: src
    displayName: Set build number

  - template: azure-pipelines/dotnet.yml
  - template: azure-pipelines/node.yml
  - template: azure-pipelines/collect-deployables.yml
  - template: azure-pipelines/collect-logs.yml

- job: Linux
  pool:
    vmImage: Ubuntu 16.04
  steps:
  - template: azure-pipelines/install-dependencies.yml
  - template: azure-pipelines/dotnet.yml
  - template: azure-pipelines/node.yml
  - template: azure-pipelines/collect-logs.yml

- job: macOS
  pool:
    vmImage: macOS 10.13
  steps:
  - template: azure-pipelines/install-dependencies.yml
  - template: azure-pipelines/dotnet.yml
  - template: azure-pipelines/node.yml
  - template: azure-pipelines/collect-logs.yml
