steps:
- script: dotnet --info
  displayName: .NET Core SDK/runtimes (on host)

- task: UseDotNet@2
  displayName: Install .NET Core SDK 2.2.300
  inputs:
    packageType: sdk
    version: 2.2.300

- task: UseDotNet@2
  displayName: Install .NET Core runtime 2.1.11
  inputs:
    packageType: runtime
    version: 2.1.11

- script: dotnet --info
  displayName: .NET Core SDK/runtimes (explicitly installed)
