steps:
- script: dotnet --info
  displayName: .NET Core SDK/runtimes (on host)

- task: UseDotNet@2
  displayName: Install .NET Core SDK 2.2.300
  inputs:
    packageType: sdk
    version: 2.2.300

- task: UseDotNet@2
  displayName: Install .NET Core runtime 1.0.16
  inputs:
    packageType: runtime
    version: 1.0.16
  condition: ne(variables['Agent.OS'], 'Linux') # workaround https://github.com/microsoft/azure-pipelines-tasks/issues/10560

- task: UseDotNet@2
  displayName: Install .NET Core runtime 1.1.13
  inputs:
    packageType: runtime
    version: 1.1.13
  condition: ne(variables['Agent.OS'], 'Linux') # workaround https://github.com/microsoft/azure-pipelines-tasks/issues/10560

- script: |
    wget https://dot.net/v1/dotnet-install.sh -O $(Agent.TempDirectory)/dotnet-install.sh
    chmod +x $(Agent.TempDirectory)/dotnet-install.sh
    $(Agent.TempDirectory)/dotnet-install.sh --install-dir $(Agent.ToolsDirectory)/dotnet -v 1.0.16 --runtime dotnet
    $(Agent.TempDirectory)/dotnet-install.sh --install-dir $(Agent.ToolsDirectory)/dotnet -v 1.1.13 --runtime dotnet
  displayName: Install .NET Core 1.0.16 and 1.1.13 runtimes
  condition: eq(variables['Agent.OS'], 'Linux') # workaround https://github.com/microsoft/azure-pipelines-tasks/issues/10560

- task: UseDotNet@2
  displayName: Install .NET Core runtime 2.0.9
  inputs:
    packageType: runtime
    version: 2.0.9

- task: UseDotNet@2
  displayName: Install .NET Core runtime 2.1.11
  inputs:
    packageType: runtime
    version: 2.1.11

- script: dotnet --info
  displayName: .NET Core SDK/runtimes (explicitly installed)
