steps:
- task: UseNode@1
  displayName: Use Node 10.x
  inputs:
    version: 10.x

- task: YarnInstaller@3
  displayName: Use yarn 1.x
  inputs:
    versionSpec: 1.x

- task: Yarn@3
  displayName: Yarn install
  inputs:
    projectDirectory: src/nerdbank-streams

- task: Yarn@3
  displayName: Yarn build
  inputs:
    projectDirectory: src/nerdbank-streams
    arguments: build

- task: Yarn@3
  displayName: Yarn test
  inputs:
    projectDirectory: src/nerdbank-streams
    arguments: test
